# Generated by Django 5.0 on 2025-07-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sweet',
        ),
    ]
